apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "keyless-signature.fullname" . }}-fulcio
  labels:
    {{- include "keyless-signature.labels" . | nindent 4 }}
data:
  config: |
    {
      "OIDCIssuers": {
        "http://dex:8888/auth": {
          "IssuerURL": "http://dex:8888/auth",
          "ClientID": "sigstore",
          "IssuerClaim": "github",
          "Type": "email"
        }
      }
    }
